#!/bin/sh
# cert-expiry-finder (part of ossobv/vcutil) // wdoekes/2016-2022
#   // Public Domain
#
# Searches for X.509 (SSL/TLS) certificates in common locations and
# enumerates the expiry days.
#
# Usage:
#
#     cert-expiry-finder        # lists all certs and days
#     cert-expiry-finder --min  # lists the soonest expiry
#     cert-expiry-finder -h     # shows help and Zabbix example
#
# See also:
#
#     cert-expiry-check
#
# In some (cron) environments, we might not find all tools (like postconf!).
# Amend the PATH so we're more likely to.
PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -u  # skip -e; we do want some results in case of failure
s='[[:blank:]]'
S='[^[:blank:]]'

global_t0=$(date +%s)  # cache the "now" value

enum_all_certs() {
    (
        enum_apache2_certs
        enum_dovecot_certs
        enum_gitlab_certs
        enum_haproxy_certs
        enum_kuberstuff_certs
        enum_mysql_wsrep_certs
        enum_nginx_certs
        enum_openvpn_certs
        enum_postfix_certs
        enum_promtail_certs
        enum_ser_certs
        enum_systemd_certs
        enum_vault_certs
        enum_zabbix_certs
    ) | LC_ALL=C sort -u
}

enum_apache2_certs() {
    find /etc/apache2/apache2.conf \
         /etc/apache2/mods-enabled/ssl.conf \
         /etc/apache2/sites-enabled/ \
        '(' -type f -o -type l ')' '!' -name '.*' -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -ne "
        s/^$s*SSLCertificateFile$s\+\($S*\).*/\1/p"
}

enum_dovecot_certs() {
    find /etc/dovecot/ '(' -type f -o -type l ')' '!' -name '.*' \
        -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -ne "
        s/^ssl_cert_file$s*=$s*\($S\+\).*/\1/p"
}

enum_gitlab_certs() {
    sed -e "
        /^nginx[[].ssl_certificate.[]]/!d
        s/[^=]*=$s*[\"']\([^\"']*\)[\"'].*/\1/
    " /etc/gitlab/gitlab.rb 2>/dev/null || true
}

enum_haproxy_certs() {
    find /etc/haproxy/ -name '*.cfg' -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -e "
        /^$s*bind$s.*${s}ssl\($\|$s\)/!d
        s/${s}crt\(-list\)\?$s\+/\n|/g" |
    sed -e "/^|/!d;s/^.//;s/$s.*//" | while read f; do
      test -d "$f" && find "$f" -maxdepth 1 -type f || echo "$f"; done
}

enum_kuberstuff_certs() {
    # Expected paths:
    # /var/lib/kube-apiserver/pki
    # /var/lib/kube-controller-manager/pki
    # /var/lib/kube-scheduler/pki
    # /var/lib/kubelet/pki
    # /etc/kubernetes/pki
    # Exclude "-----BEGIN PUBLIC KEY-----" from access-token.crt.
    find /var/lib/kube*/pki \
         /etc/kubernetes/pki \
        -name '*.crt' 2>/dev/null |
        xargs --no-run-if-empty grep -l '^-----BEGIN CERTIFICATE-----'
        # no dollar, CR optional
}

enum_mysql_wsrep_certs() {
    find /etc/mysql/ -type f -name '*.cnf' -print0 |
        xargs --no-run-if-empty -0 sed -ne "
            s/^\(tcert\|tca\|ssl-cert\|ssl-ca\)$s*=$s*\($S*\).*/\2/p"
    find /etc/mysql/ -type f -name '*.cnf' -print0 |
        xargs --no-run-if-empty -0 grep 'wsrep_provider_options' |
            tr ';' '\n' | sed -ne "
                s/^\(socket.ssl_ca\|socket.ssl_cert\)=\($S*\).*/\2/p"
}

enum_nginx_certs() {
    find /etc/nginx/nginx.conf \
         /etc/nginx/conf.d/ \
         /etc/nginx/configs/ \
         /etc/nginx/sites-enabled/ \
        '(' -type f -o -type l ')' '!' -name '.*' -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -ne "
        s/^$s*ssl_certificate$s\+\($S*\).*;.*/\1/p"
}

enum_openvpn_certs() {
    local f
    find /etc/openvpn /etc/openvpn-nl -maxdepth 2 -name '*.conf' 2>/dev/null |
    while read -r f; do
        local fpath certs cert
        certs=$(cat "$f" | sed -ne "
            s/^$s*\(ca\|cert\|crl-verify\)$s\+\([^[:blank:]#]*\).*/\2/p")
        fpath=${f%/*}
        for cert in $certs; do
            test "${cert#/}" = "${cert}" && cert=$fpath/$cert
            echo "$cert"
        done
    done
}

enum_postfix_certs() {
    postconf 'smtpd_tls_cert_file' 2>/dev/null |
    sed -e 's/.* = *//'
}

enum_promtail_certs() {
    find /etc/promtail/ -name *.yaml -print0 2>/dev/null |
        xargs --no-run-if-empty -0 sed -ne "
            s/^$s*cert_file$s*:$s*\($S*\).*/\1/p"
}

enum_ser_certs() {
    # tls_certificate = "XYZ"
    find /etc/kamailio/ /etc/opensips/ /etc/ser/ \
        '(' -type f -o -type l ')' -name '*.cfg' -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -ne "
        s/^$s*tls_certificate$s*=$s*\"\($S*\)\".*/\1/p"

    # modparam("tls", "certificate", "XYZ")
    find /etc/kamailio/ /etc/opensips/ /etc/ser/ \
        '(' -type f -o -type l ')' -name '*.cfg' -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -ne "
        s/^$s*modparam(\"tls\(_mgm\)\?\",$s*\"certificate\"$s*,$s*\"\([^\"]*\)\".*/\2/p"
}

enum_systemd_certs() {
    find /etc/systemd/ -maxdepth 2 -name *.conf -print0 2>/dev/null |
        xargs --no-run-if-empty -0 sed -ne "
            s/^ServerCertificateFile$s*=$s*\($S*\).*/\1/p"
}

enum_vault_certs() {
    find /etc/vault.d/ -type f -name '*.hcl' -print0 2>/dev/null |
    xargs --no-run-if-empty -0 sed -ne "
        s/^$s*tls_cert_file$s*=$s*\"\([^\"]*\)\".*/\1/p"
}

enum_zabbix_certs() {
    find /etc/zabbix/ -maxdepth 2 -name *.conf -print0 2>/dev/null |
        xargs --no-run-if-empty -0 sed -ne "
            s/^TLSCertFile$s*=$s*\($S*\).*/\1/p"
}

list_cert_expiry_days() {
    local file expiry
    for file in "$@"; do
        expiry=$(expiry_after "$file")
        if test -n "$expiry"; then
            expiry=$((expiry / 86400))
            printf '%-7d %s\n' $expiry "$file"
        else
            echo "expiry parse error: $file" >&2
        fi
    done
}

expiry_after() {
    local file date tn td
    file=$1
    case $file in
    *.crl|*/crl.pem)
        date=$(openssl crl -in "$file" -noout -nextupdate |
               sed -e '/nextUpdate=/!d;s/.*=//')
        ;;
    *)
        date=$(openssl x509 -in "$file" -noout -dates |
               sed -e '/notAfter=/!d;s/.*=//')
        ;;
    esac
    tn=$(date --date="$date" +%s)
    td=$((tn - global_t0))
    echo $td
}

if test $# -eq 0; then
    list_cert_expiry_days $(enum_all_certs)
elif test $# -eq 1 && test "$1" = "--min"; then
    list_cert_expiry_days $(enum_all_certs) |
    awk '{if(n==""||$1<n){n=$1}}END{if(n!=""){print n}else{exit 1}}'
else
    cat >&2 << __EOF__
Usage: cert-expiry-finder [--min]

Enumerates all X.509 (SSL/TLS) certificates from common known locations
like nginx, apache2, postfix, and lists how many days there are left to
expiry.

Zabbix example:

    # The shortest amount of days before expiry of all certificates found on
    # this machine.
    UserParameter=cert.server.minexpiry,cert-expiry-finder --min || echo 5555

__EOF__
fi

# vim: set ts=8 sw=4 sts=4 et ai:
