#!/bin/sh
# fwdiff (part of ossobv/vcutil) // wdoekes/2022,2025 // Public Domain
#
# Generic (coarse) monitoring of iptables rules.
#
# Optionally add /etc/default/fwdiff to override fwdiff_dump_override().
#
set -eu
LSMOD=$(lsmod 2>/dev/null)
if test $? -ne 0 -o $(id -u) -ne 0; then
    echo "Failed to get modules or root status; root perms required" >&2
    exit 1
fi

dump_iptables() {
    local tables="$(echo "$LSMOD" |
        sed '/^iptable_/!d;/.*[[:blank:]]0$/d;s/^[^_]*_//;s/[[:blank:]].*//' |
        sort)"
    if test -z "$tables"; then
        #echo 'fwdiff: no ip4 tables found, error?' >&2
        # I guess, nftables? Does not add modules for nothing.
        tables='filter nat mangle raw'
    fi
    for table in $tables; do
        iptables -t $table -S | sed -e "s/^/iptables -t $table /"
    done
}

dump_ip6tables() {
    local tables="$(echo "$LSMOD" |
        sed '/^ip6table_/!d;/.*[[:blank:]]0$/d;s/^[^_]*_//;s/[[:blank:]].*//' |
        sort)"
    if test -z "$tables"; then
        #echo 'fwdiff: no ip6 tables found, error?' >&2
        # I guess, nftables? Does not add modules for nothing.
        tables='filter nat mangle raw'
    fi
    for table in $tables; do
        ip6tables -t $table -S | sed -e "s/^/ip6tables -t $table /"
    done
}

dump_ipset() {
    if ! ipset --version >/dev/null 2>&1; then
        return
    fi

    # Sort options to sort by:
    # - ipset name (field 2-2: ignore blanks (b))
    # - then "create" before "add" (field 1-1: reverse sort (r))
    # - lastly sort the rest of the line for IPs (field 3: version sort (V))
    ipset -q save 2>/dev/null |
        LC_ALL=C sort -k 2bV,2 -k 1br,1 -k 3bV |
        sed -e 's/ initval 0x[0-9a-f]*//;s/^/ipset /'
}

fwdiff_dump() {
    # ipset needs to come before iptables if we want to use the sets
    dump_ipset

    dump_iptables
    dump_ip6tables
}

fwdiff_dump_override() {
    # Override this, maybe with: | grep -v '^iptables -t filter -A ...'
    fwdiff_dump
}

DB=/var/lib/fwdiff.db
if test -r /etc/default/fwdiff; then
    . /etc/default/fwdiff
fi

TEMP=$(mktemp)
trap 'rm $TEMP' EXIT

case ${1:-show} in
show)
    fwdiff_dump_override >"$TEMP"
    CHANGES=$(diff -NU0 "$DB" "$TEMP" | sed -e '1,3d')
    if test -n "$CHANGES"; then
        printf '%s\n' "$CHANGES"
        exit 1
    fi
    exit 0
    ;;
write)
    fwdiff_dump_override >"$DB.new"
    cp -a "$DB" "$DB.old" 2>/dev/null || true
    mv "$DB.new" "$DB"
    echo "Wrote to $DB"
    if test "${2:-}" = "-v"; then
        diff -NU0 "$DB.old" "$DB" | sed -e '1,3d'
    fi
    exit 0
    ;;
dump)
    fwdiff_dump_override
    exit 0
    ;;
*)
    echo 'Usage: fwdiff show|write|dump' >&2
    exit 1
    ;;
esac
