#!/bin/sh
# git-hook-postcommit-coloremail (part of ossobv/vcutil) // wdoekes/2014
#   // Public Domain
#
# Sends out a nice colored e-mail with the committed changeset for
# each committed revision. It uses the awesome vim(1) syntax
# highlighting to colorize the patch files.
#
# Use this for git repositories that are local only.
#
# Installation:
#
#     $ cd /path/to/local/git/checkout/.git
#     $ ln -s /usr/local/bin/svn-hook-postcommit-coloremail hooks/post-commit
#
# Usage:
#
#     git-hook-postcommit-coloremail
#
# FAQ:
#
#     * I don't want my passwords mailed.
#
#       Use the #CENSORED\# tag on the same line, see censored-for-email.
#
#     * Committing takes longer than before.
#
#       Yes, the email is generated during commit time. That means that
#       the submitter of a commit has to wait until the e-mail is
#       generated and sent. We could disown this job and have it run in
#       the background, if needed.
#
#     * Does it cope with non-ASCII?
#
#       It is encoding-agnostic. The mail however assumes everything is
#       in UTF-8. (And also the subject gets sent verbatim. Any
#       non-ASCII in the summary line will be technically invalid, but
#       parsed by modern e-mail clients.)
#

# Settings:
MAIL_FROM="noreply@`hostname -d`"
MAIL_TO="commits@localhost" # space separated list of recipients
SUBJECT='[$PROJECT] r$REV: $SUMMARY' # these get expanded later

# Fetch data:
REV="`git log -1 HEAD --format=%h`"
PROJECT="`hostname -s`:`basename "\`pwd\`"`"
SUMMARY="`git log -1 HEAD --format=%s`"
CENSOR=`which censored-for-email 2>/dev/null || which cat`

colormail()
{
	txt="`mktemp`" # no --suffix.. debian does not like
	head -n1000 > "$txt" # limit mail to 1000 lines
	html="$txt.html" # unsafe, but we don't care
	yes |
		vim -n -T builtin_ansi -c 'syn on|set syn=diff|set bg=dark|runtime syntax/2html.vim|wqa' "$txt" 2>&1 >/dev/null |
		grep -v '^Vim: Warning: '
	# mail the stuff
	(
		echo 'This is MIME mail.'
		echo
		echo '--e89a8f3ba551e83b0e04cdf77b8c'
		echo 'Content-Type: text/plain; charset=utf-8'
		echo
		cat "$txt"
		echo
		echo '--e89a8f3ba551e83b0e04cdf77b8c'
		echo 'Content-Type: text/html; charset=utf-8'
		echo
		cat "$txt.html"
		echo
		echo '--e89a8f3ba551e83b0e04cdf77b8c--'
	) | mail -a 'MIME-Version: 1.0' \
		 -a 'Content-Type: multipart/alternative; boundary=e89a8f3ba551e83b0e04cdf77b8c' \
		 "$@"
	# clean up
	rm "$txt" "$html"
}

(
	# Print log message and diff
	git show -p -1 HEAD
	echo
) | "$CENSOR" | colormail -s "`eval echo "$SUBJECT"`" -a "From: $MAIL_FROM" $MAIL_TO
