#!/usr/bin/env python
# renum (part of ossobv/vcutil) // wdoekes/2025 // Public Domain
#
# Replace numeric codes (errno, syscall, etc.) with symbolic names,
# based on mapping rules: reverse-enum.
#
# You can quickly look up errno or a syscall number, using:
#
#   $ renum errno <<<'1'
#   EPERM (1)
#
#   $ renum syscall <<<'1'
#   write (1)
#
# But more useful is to post-process values from somewhere else. For
# instance you might have a bpftrace(8) program that outputs various
# counts of errno, syscall numbers or a combination of the two:
#
#   @errno[1] = 5
#   @syscall[1] = 7
#   @syscall_errno[1, 1] = 9
#
# If you pipe that through renum as follows:
#
#   renum \
#     1=syscall,2=errno,^@syscall_errno \
#     1=errno,^@errno \
#     1=syscall,^@syscall
#
# or, using the shorthand form:
#
#   renum s,e,^@syscall_errno e,^@errno s,^@syscall
#
# you will see this:
#
#   @errno[EPERM (1)] = 5
#   @syscall[write (1)] = 7
#   @syscall_errno[write (1), EPERM (1)] = 9
#
# (Note how the "^@syscall_errno" regex needs to be before "^@syscall", or
# the latter would match first.)
#
# See also: ausyscall(8) in the auditd package.
#
import sys
from argparse import ArgumentParser, RawTextHelpFormatter
from os import environ
from re import compile as re_compile
from unittest import TestCase

# /usr/include/asm-generic/errno.h
# /usr/include/asm-generic/errno-base.h
ERRNO = {
    1: 'EPERM',
    2: 'ENOENT',
    3: 'ESRCH',
    4: 'EINTR',
    5: 'EIO',
    6: 'ENXIO',
    7: 'E2BIG',
    8: 'ENOEXEC',
    9: 'EBADF',
    10: 'ECHILD',
    11: 'EAGAIN',
    12: 'ENOMEM',
    13: 'EACCES',
    14: 'EFAULT',
    15: 'ENOTBLK',
    16: 'EBUSY',
    17: 'EEXIST',
    18: 'EXDEV',
    19: 'ENODEV',
    20: 'ENOTDIR',
    21: 'EISDIR',
    22: 'EINVAL',
    23: 'ENFILE',
    24: 'EMFILE',
    25: 'ENOTTY',
    26: 'ETXTBSY',
    27: 'EFBIG',
    28: 'ENOSPC',
    29: 'ESPIPE',
    30: 'EROFS',
    31: 'EMLINK',
    32: 'EPIPE',
    33: 'EDOM',
    34: 'ERANGE',
    35: 'EDEADLK',
    36: 'ENAMETOOLONG',
    37: 'ENOLCK',
    38: 'ENOSYS',
    39: 'ENOTEMPTY',
    40: 'ELOOP',
    42: 'ENOMSG',
    43: 'EIDRM',
    44: 'ECHRNG',
    45: 'EL2NSYNC',
    46: 'EL3HLT',
    47: 'EL3RST',
    48: 'ELNRNG',
    49: 'EUNATCH',
    50: 'ENOCSI',
    51: 'EL2HLT',
    52: 'EBADE',
    53: 'EBADR',
    54: 'EXFULL',
    55: 'ENOANO',
    56: 'EBADRQC',
    57: 'EBADSLT',
    59: 'EBFONT',
    60: 'ENOSTR',
    61: 'ENODATA',
    62: 'ETIME',
    63: 'ENOSR',
    64: 'ENONET',
    65: 'ENOPKG',
    66: 'EREMOTE',
    67: 'ENOLINK',
    68: 'EADV',
    69: 'ESRMNT',
    70: 'ECOMM',
    71: 'EPROTO',
    72: 'EMULTIHOP',
    73: 'EDOTDOT',
    74: 'EBADMSG',
    75: 'EOVERFLOW',
    76: 'ENOTUNIQ',
    77: 'EBADFD',
    78: 'EREMCHG',
    79: 'ELIBACC',
    80: 'ELIBBAD',
    81: 'ELIBSCN',
    82: 'ELIBMAX',
    83: 'ELIBEXEC',
    84: 'EILSEQ',
    85: 'ERESTART',
    86: 'ESTRPIPE',
    87: 'EUSERS',
    88: 'ENOTSOCK',
    89: 'EDESTADDRREQ',
    90: 'EMSGSIZE',
    91: 'EPROTOTYPE',
    92: 'ENOPROTOOPT',
    93: 'EPROTONOSUPPORT',
    94: 'ESOCKTNOSUPPORT',
    95: 'EOPNOTSUPP',
    96: 'EPFNOSUPPORT',
    97: 'EAFNOSUPPORT',
    98: 'EADDRINUSE',
    99: 'EADDRNOTAVAIL',
    100: 'ENETDOWN',
    101: 'ENETUNREACH',
    102: 'ENETRESET',
    103: 'ECONNABORTED',
    104: 'ECONNRESET',
    105: 'ENOBUFS',
    106: 'EISCONN',
    107: 'ENOTCONN',
    108: 'ESHUTDOWN',
    109: 'ETOOMANYREFS',
    110: 'ETIMEDOUT',
    111: 'ECONNREFUSED',
    112: 'EHOSTDOWN',
    113: 'EHOSTUNREACH',
    114: 'EALREADY',
    115: 'EINPROGRESS',
    116: 'ESTALE',
    117: 'EUCLEAN',
    118: 'ENOTNAM',
    119: 'ENAVAIL',
    120: 'EISNAM',
    121: 'EREMOTEIO',
    122: 'EDQUOT',
    123: 'ENOMEDIUM',
    124: 'EMEDIUMTYPE',
    125: 'ECANCELED',
    126: 'ENOKEY',
    127: 'EKEYEXPIRED',
    128: 'EKEYREVOKED',
    129: 'EKEYREJECTED',
    130: 'EOWNERDEAD',
    131: 'ENOTRECOVERABLE',
    132: 'ERFKILL',
    133: 'EHWPOISON',
}
# /usr/include/asm-generic/signal.h
SIGNAL = {
    1: 'SIGHUP',
    2: 'SIGINT',
    3: 'SIGQUIT',
    4: 'SIGILL',
    5: 'SIGTRAP',
    6: 'SIGABRT',
    7: 'SIGBUS',
    8: 'SIGFPE',
    9: 'SIGKILL',
    10: 'SIGUSR1',
    11: 'SIGSEGV',
    12: 'SIGUSR2',
    13: 'SIGPIPE',
    14: 'SIGALRM',
    15: 'SIGTERM',
    16: 'SIGSTKFLT',
    17: 'SIGCHLD',
    18: 'SIGCONT',
    19: 'SIGSTOP',
    20: 'SIGTSTP',
    21: 'SIGTTIN',
    22: 'SIGTTOU',
    23: 'SIGURG',
    24: 'SIGXCPU',
    25: 'SIGXFSZ',
    26: 'SIGVTALRM',
    27: 'SIGPROF',
    28: 'SIGWINCH',
    29: 'SIGIO',
    30: 'SIGPWR',
    31: 'SIGSYS',
}
# /usr/include/x86_64-linux-gnu/asm/unistd_64.h
SYSCALL = {  # (linux, x86_64)
    0: 'read',
    1: 'write',
    2: 'open',
    3: 'close',
    4: 'stat',
    5: 'fstat',
    6: 'lstat',
    7: 'poll',
    8: 'lseek',
    9: 'mmap',
    10: 'mprotect',
    11: 'munmap',
    12: 'brk',
    13: 'rt_sigaction',
    14: 'rt_sigprocmask',
    15: 'rt_sigreturn',
    16: 'ioctl',
    17: 'pread64',
    18: 'pwrite64',
    19: 'readv',
    20: 'writev',
    21: 'access',
    22: 'pipe',
    23: 'select',
    24: 'sched_yield',
    25: 'mremap',
    26: 'msync',
    27: 'mincore',
    28: 'madvise',
    29: 'shmget',
    30: 'shmat',
    31: 'shmctl',
    32: 'dup',
    33: 'dup2',
    34: 'pause',
    35: 'nanosleep',
    36: 'getitimer',
    37: 'alarm',
    38: 'setitimer',
    39: 'getpid',
    40: 'sendfile',
    41: 'socket',
    42: 'connect',
    43: 'accept',
    44: 'sendto',
    45: 'recvfrom',
    46: 'sendmsg',
    47: 'recvmsg',
    48: 'shutdown',
    49: 'bind',
    50: 'listen',
    51: 'getsockname',
    52: 'getpeername',
    53: 'socketpair',
    54: 'setsockopt',
    55: 'getsockopt',
    56: 'clone',
    57: 'fork',
    58: 'vfork',
    59: 'execve',
    60: 'exit',
    61: 'wait4',
    62: 'kill',
    63: 'uname',
    64: 'semget',
    65: 'semop',
    66: 'semctl',
    67: 'shmdt',
    68: 'msgget',
    69: 'msgsnd',
    70: 'msgrcv',
    71: 'msgctl',
    72: 'fcntl',
    73: 'flock',
    74: 'fsync',
    75: 'fdatasync',
    76: 'truncate',
    77: 'ftruncate',
    78: 'getdents',
    79: 'getcwd',
    80: 'chdir',
    81: 'fchdir',
    82: 'rename',
    83: 'mkdir',
    84: 'rmdir',
    85: 'creat',
    86: 'link',
    87: 'unlink',
    88: 'symlink',
    89: 'readlink',
    90: 'chmod',
    91: 'fchmod',
    92: 'chown',
    93: 'fchown',
    94: 'lchown',
    95: 'umask',
    96: 'gettimeofday',
    97: 'getrlimit',
    98: 'getrusage',
    99: 'sysinfo',
    100: 'times',
    101: 'ptrace',
    102: 'getuid',
    103: 'syslog',
    104: 'getgid',
    105: 'setuid',
    106: 'setgid',
    107: 'geteuid',
    108: 'getegid',
    109: 'setpgid',
    110: 'getppid',
    111: 'getpgrp',
    112: 'setsid',
    113: 'setreuid',
    114: 'setregid',
    115: 'getgroups',
    116: 'setgroups',
    117: 'setresuid',
    118: 'getresuid',
    119: 'setresgid',
    120: 'getresgid',
    121: 'getpgid',
    122: 'setfsuid',
    123: 'setfsgid',
    124: 'getsid',
    125: 'capget',
    126: 'capset',
    127: 'rt_sigpending',
    128: 'rt_sigtimedwait',
    129: 'rt_sigqueueinfo',
    130: 'rt_sigsuspend',
    131: 'sigaltstack',
    132: 'utime',
    133: 'mknod',
    134: 'uselib',
    135: 'personality',
    136: 'ustat',
    137: 'statfs',
    138: 'fstatfs',
    139: 'sysfs',
    140: 'getpriority',
    141: 'setpriority',
    142: 'sched_setparam',
    143: 'sched_getparam',
    144: 'sched_setscheduler',
    145: 'sched_getscheduler',
    146: 'sched_get_priority_max',
    147: 'sched_get_priority_min',
    148: 'sched_rr_get_interval',
    149: 'mlock',
    150: 'munlock',
    151: 'mlockall',
    152: 'munlockall',
    153: 'vhangup',
    154: 'modify_ldt',
    155: 'pivot_root',
    156: '_sysctl',
    157: 'prctl',
    158: 'arch_prctl',
    159: 'adjtimex',
    160: 'setrlimit',
    161: 'chroot',
    162: 'sync',
    163: 'acct',
    164: 'settimeofday',
    165: 'mount',
    166: 'umount2',
    167: 'swapon',
    168: 'swapoff',
    169: 'reboot',
    170: 'sethostname',
    171: 'setdomainname',
    172: 'iopl',
    173: 'ioperm',
    174: 'create_module',
    175: 'init_module',
    176: 'delete_module',
    177: 'get_kernel_syms',
    178: 'query_module',
    179: 'quotactl',
    180: 'nfsservctl',
    181: 'getpmsg',
    182: 'putpmsg',
    183: 'afs_syscall',
    184: 'tuxcall',
    185: 'security',
    186: 'gettid',
    187: 'readahead',
    188: 'setxattr',
    189: 'lsetxattr',
    190: 'fsetxattr',
    191: 'getxattr',
    192: 'lgetxattr',
    193: 'fgetxattr',
    194: 'listxattr',
    195: 'llistxattr',
    196: 'flistxattr',
    197: 'removexattr',
    198: 'lremovexattr',
    199: 'fremovexattr',
    200: 'tkill',
    201: 'time',
    202: 'futex',
    203: 'sched_setaffinity',
    204: 'sched_getaffinity',
    205: 'set_thread_area',
    206: 'io_setup',
    207: 'io_destroy',
    208: 'io_getevents',
    209: 'io_submit',
    210: 'io_cancel',
    211: 'get_thread_area',
    212: 'lookup_dcookie',
    213: 'epoll_create',
    214: 'epoll_ctl_old',
    215: 'epoll_wait_old',
    216: 'remap_file_pages',
    217: 'getdents64',
    218: 'set_tid_address',
    219: 'restart_syscall',
    220: 'semtimedop',
    221: 'fadvise64',
    222: 'timer_create',
    223: 'timer_settime',
    224: 'timer_gettime',
    225: 'timer_getoverrun',
    226: 'timer_delete',
    227: 'clock_settime',
    228: 'clock_gettime',
    229: 'clock_getres',
    230: 'clock_nanosleep',
    231: 'exit_group',
    232: 'epoll_wait',
    233: 'epoll_ctl',
    234: 'tgkill',
    235: 'utimes',
    236: 'vserver',
    237: 'mbind',
    238: 'set_mempolicy',
    239: 'get_mempolicy',
    240: 'mq_open',
    241: 'mq_unlink',
    242: 'mq_timedsend',
    243: 'mq_timedreceive',
    244: 'mq_notify',
    245: 'mq_getsetattr',
    246: 'kexec_load',
    247: 'waitid',
    248: 'add_key',
    249: 'request_key',
    250: 'keyctl',
    251: 'ioprio_set',
    252: 'ioprio_get',
    253: 'inotify_init',
    254: 'inotify_add_watch',
    255: 'inotify_rm_watch',
    256: 'migrate_pages',
    257: 'openat',
    258: 'mkdirat',
    259: 'mknodat',
    260: 'fchownat',
    261: 'futimesat',
    262: 'newfstatat',
    263: 'unlinkat',
    264: 'renameat',
    265: 'linkat',
    266: 'symlinkat',
    267: 'readlinkat',
    268: 'fchmodat',
    269: 'faccessat',
    270: 'pselect6',
    271: 'ppoll',
    272: 'unshare',
    273: 'set_robust_list',
    274: 'get_robust_list',
    275: 'splice',
    276: 'tee',
    277: 'sync_file_range',
    278: 'vmsplice',
    279: 'move_pages',
    280: 'utimensat',
    281: 'epoll_pwait',
    282: 'signalfd',
    283: 'timerfd_create',
    284: 'eventfd',
    285: 'fallocate',
    286: 'timerfd_settime',
    287: 'timerfd_gettime',
    288: 'accept4',
    289: 'signalfd4',
    290: 'eventfd2',
    291: 'epoll_create1',
    292: 'dup3',
    293: 'pipe2',
    294: 'inotify_init1',
    295: 'preadv',
    296: 'pwritev',
    297: 'rt_tgsigqueueinfo',
    298: 'perf_event_open',
    299: 'recvmmsg',
    300: 'fanotify_init',
    301: 'fanotify_mark',
    302: 'prlimit64',
    303: 'name_to_handle_at',
    304: 'open_by_handle_at',
    305: 'clock_adjtime',
    306: 'syncfs',
    307: 'sendmmsg',
    308: 'setns',
    309: 'getcpu',
    310: 'process_vm_readv',
    311: 'process_vm_writev',
    312: 'kcmp',
    313: 'finit_module',
    314: 'sched_setattr',
    315: 'sched_getattr',
    316: 'renameat2',
    317: 'seccomp',
    318: 'getrandom',
    319: 'memfd_create',
    320: 'kexec_file_load',
    321: 'bpf',
    322: 'execveat',
    323: 'userfaultfd',
    324: 'membarrier',
    325: 'mlock2',
    326: 'copy_file_range',
    327: 'preadv2',
    328: 'pwritev2',
    329: 'pkey_mprotect',
    330: 'pkey_alloc',
    331: 'pkey_free',
    332: 'statx',
    333: 'io_pgetevents',
    334: 'rseq',
    424: 'pidfd_send_signal',
    425: 'io_uring_setup',
    426: 'io_uring_enter',
    427: 'io_uring_register',
    428: 'open_tree',
    429: 'move_mount',
    430: 'fsopen',
    431: 'fsconfig',
    432: 'fsmount',
    433: 'fspick',
    434: 'pidfd_open',
    435: 'clone3',
    436: 'close_range',
    437: 'openat2',
    438: 'pidfd_getfd',
    439: 'faccessat2',
    440: 'process_madvise',
    441: 'epoll_pwait2',
    442: 'mount_setattr',
    443: 'quotactl_fd',
    444: 'landlock_create_ruleset',
    445: 'landlock_add_rule',
    446: 'landlock_restrict_self',
    447: 'memfd_secret',
    448: 'process_mrelease',
    449: 'futex_waitv',
    450: 'set_mempolicy_home_node',
    451: 'cachestat',
    452: 'fchmodat2',
    453: 'map_shadow_stack',
    454: 'futex_wake',
    455: 'futex_wait',
    456: 'futex_requeue',
    457: 'statmount',
    458: 'listmount',
    459: 'lsm_get_self_attr',
    460: 'lsm_set_self_attr',
    461: 'lsm_list_modules',
}

FIELDS = {
    'errno': ERRNO,
    'signal': SIGNAL,
    'syscall': SYSCALL,
}


def build_argparser():
    p = ArgumentParser(
        prog='renum',
        formatter_class=RawTextHelpFormatter,
        description=(
            'Replace numeric codes (errno, syscall, etc.) with symbolic '
            'names,\n'
            'based on mapping rules: re(verse-e)num.\n'
            '\n'
            'Common usage is enriching bpftrace(8) @map output:\n'
            '\n'
            '  bpftrace -e \'\n'
            '    tracepoint:raw_syscalls:sys_exit {\n'
            '      if (args->id < 0) { @by_errno[-args->id] = count(); }\n'
            '    }\n'
            '    interval:s:5 {\n'
            '      print("---"); print(@by_errno); clear(@by_errno);\n'
            '    }\'\n'
            '\n'
            'This outputs these numeric constants:\n'
            '\n'
            '  ---\n'
            '  @by_errno[512]: 3\n'
            '  @by_errno[13]: 16\n'
            '  @by_errno[11]: 17938\n'
            '  @by_errno[2]: 70107\n'
            '\n'
            'Piping through "renum errno,^@by_errno" gives the constants a '
            'symbolic name:\n'
            '\n'
            '  ---\n'
            '  @by_errno[512]: 3\n'
            '  @by_errno[EACCES (13)]: 16\n'
            '  @by_errno[EAGAIN (11)]: 17938\n'
            '  @by_errno[ENOENT (2)]: 70107\n'))
    p.add_argument(
        'rules',
        metavar='RULE',
        type=Rule,
        nargs='+',
        help=(
            'Mapping rule(s) in the form '
            '"field=map[,field=map,...[,^regex]]".\n'
            'Examples:\n'
            '  renum "1=errno,2=syscall,^@by_syscall_errno"\n'
            '  renum "s,e,^@"\n'
            '  renum "1=e,^@by_errno" "1=s,^@by_syscall"\n'
            '\n'
            'Shorthand maps: e=errno, s=syscall, sig=signal.\n'
            'Regex must start with "^" if given.\n'
            '\n'
            'Only the first matching rule will be used, so you need regexes\n'
            'for all rules except the last.'))

    return p


class Rule:
    FIELD_ALIASES = {
        # Names
        'errno': 'errno',
        'signal': 'signal',
        'syscall': 'syscall',
        # Aliases
        'e': 'errno',
        'sig': 'signal',
        's': 'syscall',
    }

    def __init__(self, fmt):
        """
        Decode fmt [field=]map[,[field=]map][,^filter] to mappings and regex
        """
        replace_maps = {}
        replace_maps_nextidx = 1
        filter_re = None

        parts = fmt.split(',')
        for idx, part in enumerate(parts):
            if part.startswith('^'):
                filter_re = re_compile(','.join(parts[idx:]))
                break

            if '=' in part:
                field, map_ = part.split('=', 1)
                field = int(field)
            else:
                field = replace_maps_nextidx
                map_ = part

            if map_ not in self.FIELD_ALIASES:
                raise ValueError(f'unexpected map name {map_}')

            replace_maps[field] = self.FIELD_ALIASES[map_]
            replace_maps_nextidx = field + 1

        self.replace_maps = replace_maps
        self.filter_re = filter_re

    def select_map(self, map_):
        for field, map_name in self.replace_maps.items():
            self.replace_maps[field] = map_[map_name]


class RuleTestCase(TestCase):
    def test_fmt_basic(self):
        rule = Rule('4=syscall,2=errno,3=signal')
        self.assertIsNone(rule.filter_re)
        self.assertEqual(rule.replace_maps, {
            4: 'syscall', 2: 'errno', 3: 'signal'})

    def test_fmt_no_field(self):
        rule = Rule('syscall,signal,errno')
        self.assertIsNone(rule.filter_re)
        self.assertEqual(rule.replace_maps, {
            1: 'syscall', 2: 'signal', 3: 'errno'})

    def test_fmt_one_field_then_continue_counting(self):
        rule = Rule('3=syscall,signal,errno')
        self.assertIsNone(rule.filter_re)
        self.assertEqual(rule.replace_maps, {
            3: 'syscall', 4: 'signal', 5: 'errno'})

    def test_fmt_one_field_then_continue_counting_2(self):
        rule = Rule('syscall,5=signal,errno')
        self.assertIsNone(rule.filter_re)
        self.assertEqual(rule.replace_maps, {
            1: 'syscall', 5: 'signal', 6: 'errno'})

    def test_fmt_regex(self):
        rule = Rule('^@')
        self.assertEqual(rule.filter_re, re_compile('^@'))
        self.assertEqual(rule.replace_maps, {})

    def test_fmt_shorthand_and_regex(self):
        rule = Rule('s,e,^@by_syscall_errno')
        self.assertEqual(rule.filter_re, re_compile('^@by_syscall_errno'))
        self.assertEqual(rule.replace_maps, {
            1: 'syscall', 2: 'errno'})

    def test_fmt_illegal(self):
        with self.assertRaises(ValueError):
            Rule('bad_name')
        with self.assertRaises(ValueError):
            Rule('s,e,b')  # b does not exist
        with self.assertRaises(ValueError):
            Rule(',e,^@missing_first_value')
        with self.assertRaises(ValueError):
            Rule('s,,^@missing_second_value')
        with self.assertRaises(ValueError):
            Rule('s,')
        with self.assertRaises(ValueError):
            Rule('s,=e')
        with self.assertRaises(ValueError):
            Rule('')


class Replacer:
    """
    Callable that replaces numbers with names.

    It counts how often it is called and selects the first map based on
    the call count. Selects the second map based on the value of
    match_.group(0).
    """
    def __init__(self, maps):
        """
        Takes a map of maps. For example: {1: SYSCALLS, 3: ERRNO}

        The first match would use the SYSCALLS for replacement, the
        third match would use ERRNO. Non-matched items will be returned
        verbatim.
        """
        self._maps = maps
        self._int_position = 0

    def __call__(self, match_):
        """
        Takes a re.Match object, converts to integer, looks up replacement
        table and returns replacement if found.
        """
        self._int_position += 1

        orig = match_.group(0)
        symbol_map = self._maps.get(self._int_position)
        if symbol_map:
            num = int(orig)
            symbol = symbol_map.get(num)
            if symbol:
                return f'{symbol} ({num})'

        return orig


class ReplacerTestCase(TestCase):
    def test_replacer(self):
        map_ = {3: {5: 'foo', 15: 'bar'}, 5: {5: 'FOO', 15: 'BAR'}}
        re = re_compile(r'\b\d+\b')
        self.assertEqual(
            re.sub(Replacer(map_), '1-2'),
            '1-2')
        self.assertEqual(
            re.sub(Replacer(map_), '1-2-3'),
            '1-2-3')
        self.assertEqual(
            re.sub(Replacer(map_), '1-2-5'),
            '1-2-foo (5)')
        self.assertEqual(
            re.sub(Replacer(map_), '1-2-15-4-5-6'),
            '1-2-bar (15)-4-FOO (5)-6')


def main():
    argparser = build_argparser()
    args = argparser.parse_args()

    rules = args.rules
    for rule in rules:
        rule.select_map(FIELDS)

    # Regex to find/replace all integers
    int_re = re_compile(r'\b\d+\b')

    for line in sys.stdin:
        for rule in rules:
            if rule.filter_re is None:
                break  # no regex? then we use this rule
            if rule.filter_re.search(line):
                break  # match! we use this rule
        else:
            rule = None  # no match? no replacements

        if rule:
            line = int_re.sub(Replacer(rule.replace_maps), line)

        print(line, end='')


if __name__ == '__main__':
    if environ.get('RUNTESTS', '') not in ('', '0', 'n'):
        from unittest import main as unittest_main
        unittest_main()
    else:
        main()
