#!/bin/sh
args=`echo "$*" | sed -e 's#[^A-Za-z0-9]\+#.*#g'`
pids=`ps fax | sed -e '/[0-9] \/usr\/bin\/uwsgi.*'"$args"'/!d;s/^ *//;s/ .*//'`
test -z "$pids" && echo "Nothing matches..." >&2 && exit 1
echo "Sending restart signal to uwsgi(-cores)" $pids "..."
kill $pids
