#!/bin/sh
# wgrep (part of ossobv/vcutil) // wdoekes/2010,2015 // Public Domain
#
# Greps only these hardcoded file types for the arguments. Arguments to
# grep are still supported. Use this to search a directory tree while
# ignoring non-text files (like binary objects or images).
#
# Usage:
#
#    wgrep /path/to/location 'search-regex'
#    wgrep /path/to/location -F 'search-string'
# 
path="$1"; shift
find "$path" \
    '(' -type f -o -type l ')' \
    -regextype posix-extended \
    -regex '.*\.('\
'asp|c|cc|cfg|conf|cpp|css|cxx|erb|go|'\
'h|hpp|htm|html|java|js|less|m4|md|'\
'php|po|pp|py|rb|rst|'\
'sh|sls|sql|tpl|template|txt|xml|yaml|yml)' \
    '!' -name '*.min.*' \
    -print0 \
    | xargs -0 -- grep --color=auto "$@"
