#!/usr/bin/python3
# xdg-recent (part of ossobv/vcutil) // wdoekes/2023-2024 // Public Domain
#
# Mark files as "recently used" so they show up first in the File Browser in
# GNOME/Gtk/X. This is useful when you're editing/preparing files using
# the command line and want to upload them using a (graphical) web
# brower.
#
# Usage:
#
# - <create file1.txt>
# - xdg-recent file1.txt
# - <open graphical application, click recent, see file there>
#
# Original from unix.stackexchange.com/questions/509413 by Stephen Kitt.
# Named it xdg-recent to match xdg-open, which is the other commonly used
# tool when switching from CLI to X. Not called xdg-mark-recent because
# (a) there exists a xdg-m(ime) and (b) we may want to amend this to do
# more than just "mark".
#
# Todo:
# - add -n for do-not-mark utime()
# - do other stuff, like list/delete the RecentManager data
#
# See also: xdg-open(1) from xdg-utils.
#
import os
import sys

import gi
gi.require_version('Gtk', '3.0')

if True:
    # Indent so PEP tools don't complain.
    from gi.repository import Gtk, Gio, GLib

rec_mgr = Gtk.RecentManager.get_default()

# rd = Gtk.RecentData()
# rd.description = None
# rd.app_name = 'xdg-recent'              # free form
# rd.app_exec = '/usr/bin/xdg-open %u'    # %u = file://url, %f = filename
# rd.is_private = False

for arg in sys.argv[1:]:
    gfile = Gio.File.new_for_path(arg)

    # rd.display_name = os.path.basename(arg)
    # rd.mime_type = mimetypes.guess_type(arg)[0] or 'application/octet-stream'
    # rec_mgr.add_full(gfile.get_uri(), rd)

    # add_item() is just as capable as add_full() and it's better at
    # populating app_exec.
    rec_mgr.add_item(gfile.get_uri())

    try:
        os.utime(arg, None)
    except PermissionError:
        pass  # don't care if we cannot set mtime (for other people's files)

GLib.idle_add(Gtk.main_quit)
Gtk.main()
