#!/usr/bin/env python3
# zabdig (part of ossobv/vcutil) // wdoekes/2017-2023,2025 // Public Domain
#
# Quickly query the zabbix server for hosts and hostnames/IPs, using the
# Zabbix JSON API. It can also show current alerts and item data, and manage
# maintenance windows.
#
# Usage examples:
#
#     $ zabdig walter
#     Walter Privé                    wjdsys.example.com (zabbix-proxy2)
#     walter.internal.lan             10.32.1.5 (zabbix-proxy-lan)
#     walterdev.example.com           walterdev.example.com
#
#     $ zabdig walter.internal.lan
#     10.32.1.5
#
# Configure by setting up a ~/.zabbixrc with sections:
#
#     [myorganisation]
#     api=https://zabbix-server.example.com/api_jsonrpc.php
#     user=myusername
#     password=mypassword
#
# (If you leave out user/password it will try to get it from your Secret
# Storage API (keyring).)
#
# If you have multiple zabbix servers you wish to speak to, add
# additional sections. Use zabdig -g SECTION to select a different
# section/organisation than the first.
#
# If you have zabbix-proxies that identify as 127.0.0.1, you can add a
# DNS name (while keeping use-IP), and the DNS will be shown instead.
#
# Other modes are selected with an option, so that the first argument is
# always a (partial) hostname. Mode names can be abbreviated (--ale), and
# each mode has its own --help:
#
#     $ zabdig --alerts -S 3
#     $ zabdig --data -i 'vfs.fs.size[/,pfree]' 'web*'
#     $ zabdig --maint create --start 22:00 "kernel upgrade" 2h pve1 'db*'
#
# See zabdig --help for more info.
#
# Tip /usr/local/bin/zssh:
#
#     #!/bin/sh
#     host="$1"; shift
#
#     ip=$(zabdig "$host")
#     if ! echo "$ip" | grep -qE '^([0-9]+[.]){3}[0-9]+$'; then
#         echo "Bad IP: $ip" >&2
#         exit 1
#     fi
#
#     # Add -lSOMEUSER at tail, unless there is a "-l" somewhere already.
#     add_min_l_arg=-lSOMEUSER  # optional..
#     for arg in "$@"; do
#         test "${arg#-l}" != "$arg" && add_min_l_arg= && break
#     done
#
#     echo "(connecting to $ip ...)" >&2
#     # (move $add_min_l_arg to the left of "$@" on ssh before version 8)
#     exec ssh "$ip" "$@" $add_min_l_arg
#
# Requirements: requests (python3-requests)
#
import argparse
import configparser
import json
import os
import re
import sys

from datetime import datetime, timedelta, timezone
from datetime import time as dtime
from warnings import warn

CONF_FILE = f'{os.environ.get("XDG_CONFIG_HOME", "~/.config")}/.zabbixrc'
if not os.path.exists(os.path.expanduser(CONF_FILE)):
    CONF_FILE = '~/.zabbixrc'


class ZConfigError(ValueError):
    pass


class ZInterfaceError(IOError):
    pass


class ZLoginError(ZInterfaceError):
    pass


class ZDataError(ZInterfaceError):
    pass


class ZMaintError(Exception):
    "Something is wrong with a maintenance request; the message says what."
    pass


def glob_to_regex(pattern):
    """
    Turn a glob pattern into a regex, where only * and ? are magic.

    Simpler version of fnmatch. Hardly anyone is expected to use
    glob-style character classes. And when we're matching titles, they
    can become confusing.
    """
    return re.compile(''.join(
        '.*' if char == '*' else '.' if char == '?' else re.escape(char)
        for char in pattern), re.DOTALL)


class Needle(object):
    "Needle is used for hostname searches"
    def __init__(self, glob_pattern):
        self._exact_glob_pattern = glob_pattern
        self._exact_regex = glob_to_regex(glob_pattern)
        self._contains_regex = glob_to_regex('*{}*'.format(glob_pattern))

    def as_string(self):
        "Return the longest part that can be used in a 'contains' search"
        # So if pve?.dr.osso.cloud is passed, we'll split it into longer
        # matches and pre-search on the longest part: return ".dr.osso.cloud"
        static_parts = self._exact_glob_pattern.replace('?', '*').split('*')
        static_parts.sort(key=(lambda x: (-len(x), x)))
        return static_parts[0]  # longest non-magic part

    def is_exactly(self, string):
        "Return True if needle matches string exactly"
        return self._exact_regex.fullmatch(string) is not None

    def is_found_in(self, string):
        "Return True if needle is found somewhere in string"
        return self._contains_regex.fullmatch(string) is not None


class ZAlert(object):
    SEVERITIES = {
        0: 'N/A',   # Unclassified
        1: 'INFO',  # Info
        2: 'WARN',  # Warning
        3: 'AVG',   # Average
        4: 'HIGH',  # High
        5: 'CRIT',  # Disaster
    }

    @staticmethod
    def severity_mask_to_zabbix(mask):
        """
        We've defined severity starting with 1 for disaster as a bitmask.

        mask:   1=disaster, 2=high, 4=avg..
        zabbix: 0=unclass, 1=info, 2=warn, 3=avg, 4=high, 5=disaster
        """
        if mask == 0:
            mask = 63  # ALL

        ret = []
        if mask & 1:
            ret.append(5)  # Disaster
        if mask & 2:
            ret.append(4)  # High
        if mask & 4:
            ret.append(3)  # Average
        if mask & 8:
            ret.append(2)  # Warning
        if mask & 16:
            ret.append(1)  # Info
        if mask & 32:
            ret.append(0)  # Unclassified

        return ret

    @classmethod
    def severity_zabbix_to_str(cls, num):
        return cls.SEVERITIES[num]

    @classmethod
    def from_problem_trigger(cls, problem, trigger):
        assert trigger['value'] == '1', trigger  # 1=Problem
        assert trigger['flags'] in (
            '0',  # Normal item
            '1',  # Discovery rule
            '2',  # Item prototype
            '4',  # Auto-created item
        ), trigger  # XXX?

        hosts = trigger.pop('hosts')
        assert len(hosts) >= 1, trigger
        items = trigger.pop('items')

        zalerts = []
        items_used = 0
        for host in hosts:
            host_items = [
                item for item in items if item['hostid'] == host['hostid']]
            items_used += len(host_items)
            zalerts.append(cls(problem, trigger, host, host_items))
        assert items_used == len(items), (items_used, hosts, items)

        return zalerts

    def __init__(self, problem, trigger, host, items):
        self._problem = problem
        self._trigger = trigger
        self._host = host
        self._items = items

    @property
    def description(self):
        if not hasattr(self, '_description'):
            if self._trigger['error']:
                self._description = '{} [{}]'.format(
                    self._problem['name'], self._trigger['error'])
            else:
                self._description = self._problem['name']

            if self._problem.get('opdata'):
                self._description = '{} ({})'.format(
                    self._description, self._problem['opdata'])

            self._description = (
                self._description.replace('\n', ' ').replace('\r', ''))

        return self._description

    @property
    def hostname(self):
        return self._host['host']

    @property
    def host_enabled(self):
        assert self._host['status'] in ('0', '1')
        return self._host['status'] != '1'  # 1=disabled

    @property
    def all_items_enabled(self):
        assert all(i['status'] in ('0', '1') for i in self._items), (
            self._items)
        return all(i['status'] != '1' for i in self._items)  # 1=disabled

    @property
    def enabled(self):
        assert self._problem['suppressed'] in ('0', '1'), self._problem
        assert self._trigger['status'] in ('0', '1'), self._trigger
        if self._problem['suppressed'] == '1':
            warn('trigger suppressed on {0.hostname}: {0.description}'.format(
                self))
            return False
        return self._trigger['status'] != '1'  # 1=disabled

    @property
    def begin(self):
        if not hasattr(self, '_begin'):
            ts = int(self._problem['clock']) + (
                int(self._problem['ns']) / 1000000000.0)
            tz = timezone.utc if False else None  # FIXME?
            self._begin = datetime.fromtimestamp(ts, tz=tz)
        return self._begin

    @property
    def severity(self):
        num = int(self._problem['severity'])
        return self.severity_zabbix_to_str(num)

    def __str__(self):
        return repr(self)

    def __repr__(self):
        begin = self.begin.strftime('%Y-%m-%dT%H:%M:%S')
        return (
            'alert:{0.severity:4s} {1}: {0.description} '
            '({0.hostname})'.format(self, begin))


class ZItem(object):
    @staticmethod
    def fix_value(value):
        try:
            value = int(value)
        except ValueError:
            try:
                value = float(value)
            except ValueError:
                pass

        if isinstance(value, float):
            return '{:.2e}'.format(value)
        return str(value)

    def __init__(self, iteminfo):
        self._iteminfo = iteminfo

    @property
    def lastvalue(self):
        return self.fix_value(self._iteminfo['lastvalue'])

    @property
    def lastvalue_with_unit(self):
        if not hasattr(self, '_lastvalue_with_unit'):
            if self._iteminfo['units']:
                self._lastvalue_with_unit = ' '.join([
                    self.lastvalue, self._iteminfo['units']])
            else:
                self._lastvalue_with_unit = self.lastvalue
        return self._lastvalue_with_unit


class ZBaseHost(object):
    def __init__(self, hostinfo):
        self._hostinfo = hostinfo
        self.name = hostinfo['name']

    def get_name(self):
        return (
            self.name or  # "visible name"
            self._hostinfo['host'] or
            '<ZHost({})>'.format(self._hostinfo['hostid']))

    def __str__(self):
        return self.get_name()


class ZHost(ZBaseHost):
    def __init__(self, hostinfo, proxies):
        super(ZHost, self).__init__(hostinfo)

        if proxies and hostinfo['proxyid'] != '0':
            self.proxy = proxies[hostinfo['proxyid']]
        else:
            self.proxy = None

    def has_ip(self, ip):
        return (ip in self.get_zabbix_addr_list())

    def get_zabbix_addr_first(self):
        addr_list = self.get_zabbix_addr_list()
        if not addr_list:
            addr_list = ['NONE']
        return addr_list[0]

    def get_zabbix_addr(self):
        return ', '.join(self.get_zabbix_addr_list())

    def get_zabbix_addr_list(self):
        if not hasattr(self, '_zabbix_addr_list'):
            exit_ip4 = self.get_exit_ip4()
            ret = []
            for interface in self._hostinfo['interfaces']:
                # type 1 = Zabbix Agent
                # type 2 = SNMP
                # type 3 = IPMI
                # type 4 = JMX
                if int(interface['type']) == 1:
                    if int(interface['useip']):
                        # For zabbix proxies, we see the lo IP only.. super
                        # annoying when trying to find where it is. Hope
                        # that someone (ab)used the DNS field for more info.
                        if interface['ip'] == '127.0.0.1':
                            if interface['dns']:
                                ret.append(interface['dns'])
                            elif exit_ip4:
                                ret.append(exit_ip4)
                            else:
                                # 127.0.0.1 anyway..
                                ret.append(interface['ip'])
                        else:
                            ret.append(interface['ip'])
                    else:
                        ret.append(interface['dns'])
            self._zabbix_addr_list = list(sorted(set(ret)))

            # Always add exit_ip4; but add it last, as we may not be
            # able to access anything through it directly.
            if exit_ip4 and exit_ip4 not in self._zabbix_addr_list:
                self._zabbix_addr_list.append(exit_ip4)

        return self._zabbix_addr_list

    def get_exit_ip4(self):
        if self._hostinfo.get('inventory') == []:
            print('WARNING: {name} does not have Inventory enabled'.format(
                name=self.get_name()), file=sys.stderr)
            return None
        return self._hostinfo.get('inventory', {}).get('host_router', None)

    def is_available(self):
        if not hasattr(self, '_is_available'):
            availables = [
                iface.get('available')
                for iface in self._hostinfo['interfaces']]

            if availables:
                # Available not set on the interfaces? Then this is
                # zabbix-server<6.0
                if all(available is None for available in availables):
                    availables = [self._hostinfo.get('available')]

                availables.sort(reverse=True)
                available = availables[0]  # '2', '1', '0', None
            else:
                available = '0'  # no interfaces, no state

            # zabbix-server>=6.0 has active check polling. if the proxies
            # haven't sent any active updates, then the state is "unseen"
            if available == '0':
                if self.get_zabbix_addr() in ('127.0.0.1', ''):
                    pass
                else:
                    warn(
                        'one or more hosts have unknown state; '
                        'if you have zabbix-proxy<6.0 this is expected')
                    available = '1'  # make it 1=up

            assert available in ('0', '1', '2'), self._hostinfo
            self._is_available = available

        if self._is_available == '0':       # 0=unseen
            return None
        return (self._is_available == '1')  # 1=up, 2=down

    def is_enabled(self):
        assert self._hostinfo.get('status') in ('0', '1'), self._hostinfo
        return self._hostinfo.get('status') == '0'  # 1 is Disabled

    def __str__(self):
        if not self.is_enabled():
            return '{}--OFF'.format(self.get_name())
        elif self.is_available() is None:
            return '{}--UNKNOWN'.format(self.get_name())
        elif self.is_available() is False:
            return '{}--DOWN'.format(self.get_name())
        return self.get_name()

    def __eq__(self, other):
        return self._hostinfo['hostid'] == other._hostinfo['hostid']

    def __lt__(self, other):
        if self.name != other.name:
            return self.name < other.name
        return self._hostinfo['hostid'] < other._hostinfo['hostid']


class ZInterface(object):
    def __init__(self, url, username, password):
        if not url or not username or not password:
            raise ZConfigError(
                'cannot login without api/url, username and password')

        self.url = url
        self.username = username
        self.password = password

        self.token = None
        self.postid = 0
        self.version = self._zabbix_version()

    def _zabbix_call(self, method, params, auth=True):
        self.postid += 1
        data = {
            'jsonrpc': '2.0',
            'method': method,
            'params': params,
            'id': self.postid,
        }
        if auth:
            data['auth'] = self.token  # can be 'null'
        return self._zabbix_post(self.url, data)

    def _zabbix_post(self, url, data):
        # Imported here, so --help and the tests work without python3-requests.
        import requests

        res = requests.post(
            url, data=json.dumps(data),
            headers={'Content-Type': 'application/json-rpc'})

        try:
            js = res.json()
        except ValueError as e:
            raise ZInterfaceError(
                'JSON error "{}" in\n\n  {!r}...\n\n'.format(
                    e, res.content[0:512]), data)

        if 'error' in js:
            raise ZInterfaceError(js['error'], data)

        return js['result']

    def _zabbix_version(self) -> tuple:
        version_str = self._zabbix_call('apiinfo.version', [], False)
        return tuple(
            (int(i) if i.isdigit() else i) for i in version_str.split('.'))

    def _login(self):
        if not self.token:
            class PrivacyDict(dict):
                "Don't show username/password in stack traces."
                def __repr__(self):
                    # Yes, this repr is broken for abnormal keys, but
                    # we don't use those.
                    return '{{{}}}'.format(', '.join(
                        "'{}': '****'".format(key)
                        for key in sorted(self.keys())))

            try:
                self.token = self._zabbix_call(
                    'user.login',
                    PrivacyDict(
                        username=self.username,  # user->username since 6.0+
                        password=self.password))
            except ZInterfaceError as e:
                if e.args[0] == {
                        'code': -32602, 'message': 'Invalid params.',
                        'data': (
                            'Invalid parameter "/": unexpected parameter '
                            '"username".')}:
                    try:
                        self.token = self._zabbix_call(
                            'user.login',
                            PrivacyDict(
                                user=self.username,
                                password=self.password))
                    except ZInterfaceError as e2:
                        raise ZLoginError(*e.args) from e2
                else:
                    raise ZLoginError(*e.args) from e

    def get_alerts(self, severity, enabled_only=True):
        self._login()

        problems = self._zabbix_call(
            'problem.get',
            {'output': [
                'eventid', 'r_eventid', 'objectid', 'clock', 'ns', 'severity',
                'suppressed', 'name', 'opdata'],
             'source': 0,  # 0=trigger
             'object': 0,  # 0=trigger
             # 'groupids': [...],
             # 'hostids': [10884],
             'recent': False,  # only UNRESOLVED
             'severities': ZAlert.severity_mask_to_zabbix(severity)})

        triggerids = list(set([i['objectid'] for i in problems]))
        triggers_by_triggerid = dict(
            (i['triggerid'], i) for i in self._zabbix_call(
                'trigger.get',
                {'output': [
                    'triggerid', 'status', 'error', 'suppressed',
                    'flags', 'value'],
                 'selectHosts': ['hostid', 'host', 'status'],
                 'selectItems': ['hostid', 'status'],
                 'triggerids': triggerids}))

        alerts = []
        for problem in problems:
            trigger = triggers_by_triggerid.get(problem['objectid'])
            if not trigger:
                # This may auto-heal if the trigger was recently removed.
                # Otherwise:
                #   delete ev from events ev
                #   left join triggers tr on tr.triggerid = ev.objectid
                #   where tr.triggerid is null and
                #     ev.source = 0 and ev.object = 0;
                warn('no trigger for alert {!r}'.format(problem))
                continue

            possible_alerts = ZAlert.from_problem_trigger(problem, trigger)
            for alert in possible_alerts:
                if not alert.host_enabled:
                    # host is disabled, skip
                    continue

                if not alert.all_items_enabled:
                    # Some of the trigger items are disabled. This is generally
                    # rather annoying. Do check and re-enable them if possible.
                    # There are better ways to fix this.
                    warn('some or all items disabled in {}'.format(alert))
                    continue

                if alert.enabled or not enabled_only:
                    alerts.append(alert)

        alerts.sort(key=(lambda x: (
            x._problem['severity'], x.description, x.hostname)))

        if False:
            import pprint
            for alert in alerts:
                print(alert)
                pprint.pprint(alert._problem)
                pprint.pprint(alert._trigger)
                pprint.pprint(alert._host)
                pprint.pprint(alert._items)

        return alerts

    def get_hosts(self, hostname_needle):
        self._login()

        proxyid_label = 'proxyid'
        compat_replacement = {}
        if self.version < (7,):
            proxyid_label = 'proxy_hostid'
            compat_replacement = {'proxy_hostid': 'proxyid'}

        params = {
            'output': [
                'name', 'host', 'interfaces', proxyid_label,
                'status', 'available'],
            # 'output': ['name', 'interfaces', 'groups', 'proxy_hostid',
            #            'status'],
            'selectInventory': ['host_router'],  # or 'extend' for _all_
            'selectInterfaces': 'extend',
            'selectGroups': 'extend',
        }

        if hostname_needle:
            params['search'] = {'name': hostname_needle.as_string()}

        hosts = self._zabbix_call('host.get', params)

        for k, v in compat_replacement.items():
            for host in hosts:
                host[v] = host.pop(k)

        for host in hosts:
            try:
                if (not hostname_needle or
                        hostname_needle.is_found_in(host['name'])):
                    yield ZHost(host, self.get_proxies())
            except ZInterfaceError:
                raise
            except Exception as e:
                raise ZDataError('got err {!r} for hostinfo {}'.format(
                    e, host))

    def get_latest_data(self, hosts, items):
        self._login()

        hostids = [host._hostinfo['hostid'] for host in hosts]
        results = []

        # item = 'vfs.fs.size[*,pfree]'
        for item in items:
            params = {
                'output': [
                    'itemid', 'hostid', 'name', 'key_', 'units',
                    # 'status', 'value_type',
                    'lastclock',  # 'lastns',
                    'lastvalue', 'prevvalue'],
                'hostids': hostids,
                'search': {
                    # > If no additional options are given, this will
                    # > perform a LIKE "%...%" search.
                    'key_': item,
                },
                # > The search parameter will compare the beginning of
                # > fields, that is, perform a LIKE "...%" search instead.
                # 'startSearch': True,
                # > If set to true, enables the use of "*" as a wildcard
                # > character in the search parameter.
                'searchWildcardsEnabled': True,
                # NOTE: 'searchWildcardsEnabled' overrules
                # 'startSearch'. When using this, we need a trailing '*'
                # to get startswith functionality.
                # > If set to true, return results that match any of the
                # > criteria given in the filter or search parameter
                # > instead of all of them.
                # 'searchByAny': True,
            }
            res = self._zabbix_call('item.get', params)
            results.extend(res)

            if len(results) > 1000:
                raise ValueError('search too wide, because >1000 results')

        return [ZItem(res) for res in results]

    def get_maintenances(self, states=None):
        """
        Return the maintenances with their hosts, host groups and time
        periods.

        If the states (see maintenance_state) that are wanted are given and
        do not include EXPIRED, we skip the details of the windows whose
        active period has ended. There can be hundreds of those. We do not
        skip all expired ones: a window can be over while its active period
        is not. So the caller still needs to look at the state.
        """
        self._login()

        params = {
            'output': ['maintenanceid', 'name', 'active_since',
                       'active_till'],
            'selectHosts': ['hostid', 'name'],
            'selectHostGroups': ['groupid', 'name'],
            'selectTimeperiods': ['timeperiod_type', 'start_date',
                                  'period']}

        if states is not None and 'EXPIRED' not in states:
            now_ts = int(get_now().timestamp())
            brief = self._zabbix_call(
                'maintenance.get',
                {'output': ['maintenanceid', 'active_till']})
            params['maintenanceids'] = [
                m['maintenanceid'] for m in brief
                if int(m['active_till']) > now_ts]
            if not params['maintenanceids']:
                return []

        return self._zabbix_call('maintenance.get', params)

    def get_hostgroups(self, name_needle):
        self._login()

        return self._zabbix_call(
            'hostgroup.get',
            {'output': ['groupid', 'name'],
             'search': {'name': name_needle.as_string()}})

    def create_maintenance(self, name, hostids, groupids, active_since,
                           active_till, start_date, period):
        """
        Create a maintenance for hosts and/or host groups, with one single
        period. The active_since and active_till bound the entire
        maintenance; start_date and period (seconds) define the one time
        window inside it. Return its id.
        """
        self._login()

        params = {
            'name': name,
            'active_since': active_since,
            'active_till': active_till,
            'timeperiods': [{
                'timeperiod_type': 0,  # 0=one time only
                'start_date': start_date,
                'period': period}]}
        if hostids:
            params['hosts'] = [{'hostid': hostid} for hostid in hostids]
        if groupids:
            params['groups'] = [{'groupid': groupid} for groupid in groupids]

        try:
            res = self._zabbix_call('maintenance.create', params)
        except ZInterfaceError as e:
            if (isinstance(e.args[0], dict) and
                    'already exists' in e.args[0].get('data', '')):
                raise ZMaintError(
                    'a maintenance named {!r} already exists'.format(name))
            raise
        return res['maintenanceids'][0]

    def update_maintenance(self, maintenanceid, hostids=None, groupids=None):
        """
        Replace the hosts and/or host groups of a maintenance, whichever are
        not None. The rest of the maintenance is left alone.
        """
        self._login()

        params = {'maintenanceid': maintenanceid}
        if hostids is not None:
            params['hosts'] = [{'hostid': hostid} for hostid in hostids]
        if groupids is not None:
            params['groups'] = [{'groupid': groupid} for groupid in groupids]
        self._zabbix_call('maintenance.update', params)

    def delete_maintenances(self, maintenanceids):
        self._login()

        self._zabbix_call('maintenance.delete', list(maintenanceids))

    def get_proxies(self):
        if not hasattr(self, '_get_proxies'):
            self._login()

            host_label = 'name'
            compat_replacement = {}
            if self.version < (7,):
                host_label = 'host'
                compat_replacement = {'host': 'name'}

            proxies = self._zabbix_call(
                'proxy.get',
                {'output': [host_label, 'proxyid']})

            for k, v in compat_replacement.items():
                for proxy in proxies:
                    proxy[v] = proxy.pop(k)

            try:
                self._get_proxies = dict(
                    (proxy['proxyid'], ZBaseHost(proxy))
                    for proxy in proxies)
            except ZInterfaceError:
                raise
            except Exception as e:
                raise ZDataError('got err {!r} for proxies {}'.format(
                    e, proxies))

        return self._get_proxies


class LocalConfig(object):
    def __init__(self):
        self.config = configparser.ConfigParser()
        self.config.read(os.path.expanduser(CONF_FILE))  # silent failure
        if self.config.sections():
            self.section = self.config.sections()[0]
        else:
            self.section = None

    def select_section(self, section):
        if section in self.config.sections():
            self.section = section
        else:
            raise ZConfigError('no such section in config')

    def get(self, key):
        if not self.section:
            return None
        return self.config[self.section].get(key, None)


def get_from_secret_storage(section):
    "Requires python3-secretstorage for Freedesktop Secret Service API"
    import secretstorage
    from base64 import b64decode, b64encode
    from contextlib import closing

    with closing(secretstorage.dbus_init()) as conn:
        coll = secretstorage.get_default_collection(conn)
        if coll.is_locked():
            coll.unlock()
        # FIXME: section? or DEFAULT?
        attrs = {'application': 'zabdig'}
        if section:
            attrs['section'] = section
        res = [i for i in coll.search_items(attrs)]
        # FIXME: add 'or True' to overwrite previous passwords
        if not res:   # or True:
            import getpass

            print('No password stored; add one?', attrs)
            print('username: ', end='')
            username = input().strip()
            password = getpass.getpass('password: ')
            user_pass = b64encode(
                '{}:{}'.format(username, password).encode('utf-8'))
            # FIXME: we should check auth first before storing..
            # FIXME: we should ask for a new password if we get one of:
            # fetch failed: [{'code': -32602, 'message': 'Invalid params.',
            # 'data': 'Incorrect user name or password or account is \
            # temporarily blocked.'}]
            # fetch failed: [{'code': -32500, 'message': 'Application error.',
            # 'data': 'Incorrect user name or password or account is \
            # temporarily blocked.'}]
            coll.create_item(
                'zabdig user/pass', attributes=attrs,
                replace=True, secret=user_pass)
            res = [i for i in coll.search_items(attrs)]

        assert len(res) == 1, res
        try:
            res[0].ensure_not_locked()
        except secretstorage.exceptions.LockedException:
            dialog_dismissed = res[0].unlock()  # request user unlock
            if dialog_dismissed:
                raise
        user_pass = res[0].get_secret()
        user, password = b64decode(user_pass).decode('utf-8').split(':', 1)
        return (user, password)


def show_host(host):
    print('[{}]'.format(host.get_name()))
    print('Status = {}{}'.format(
        'ON' if host.is_available() else 'OFF',
        '' if host.is_enabled() else ' (DISABLED)'))
    print('Address = {}'.format(host.get_zabbix_addr()))
    print('ExternalIP4 = {}'.format(host.get_exit_ip4()))
    print('Proxy = {}'.format(host.proxy or ''))
    print()


def show_latest_data(hosts, items):
    if not items:
        return

    hosts_by_id = dict(
        (host._hostinfo['hostid'], host) for host in hosts)

    name_len = max(len(host._hostinfo['hostid']) for host in hosts)
    item_len = max(len(item._iteminfo['key_']) for item in items)
    value_len = max(len(item.lastvalue_with_unit) for item in items)

    items.sort(key=(lambda x: (
        x._iteminfo['key_'],
        hosts_by_id[x._iteminfo['hostid']].name)))

    for item in items:
        print(
            '{name!s:{name_len}}  {item!s:{item_len}}  '
            '{value!s:>{value_len}}'.format(
                name=hosts_by_id[item._iteminfo['hostid']].name,
                name_len=name_len,
                item=item._iteminfo['key_'],
                item_len=item_len,
                value=item.lastvalue_with_unit,
                value_len=value_len))


DURATION_RE = re.compile(r'(?:[0-9]+[smhdw])+')
DURATION_PART_RE = re.compile(r'([0-9]+)([smhdw])')
DURATION_UNITS = {'s': 1, 'm': 60, 'h': 3600, 'd': 86400, 'w': 604800}


def parse_duration(text):
    """
    Turn a duration like 90m, 2h or 1h30m into (whole minutes of) seconds.

    A unit is mandatory, because 90 is too easily mistaken for either
    minutes or seconds.
    """
    if not DURATION_RE.fullmatch(text.lower()):
        raise argparse.ArgumentTypeError(
            'invalid duration {!r}, use for example 90m, 2h or 1h30m'.format(
                text))
    seconds = sum(
        int(num) * DURATION_UNITS[unit]
        for num, unit in DURATION_PART_RE.findall(text.lower()))
    seconds = (seconds + 59) // 60 * 60  # round up to whole minutes
    if seconds == 0:
        raise argparse.ArgumentTypeError('duration must not be zero')
    return seconds


def parse_start(text):
    "Turn HH:MM into a time."
    try:
        return datetime.strptime(text, '%H:%M').time()
    except ValueError:
        raise argparse.ArgumentTypeError(
            'invalid time {!r}, use HH:MM'.format(text))


class MaintenanceWindow(object):
    """
    The times (unix timestamps, and the duration in seconds) that go into a
    maintenance. The window itself is start..end. The active period around
    it runs from midnight today to midnight after the day the window ends.
    """
    def __init__(self, start, duration, active_since, active_till):
        self.start = start
        self.duration = duration
        self.active_since = active_since
        self.active_till = active_till

    @property
    def end(self):
        return self.start + self.duration

    @classmethod
    def plan(cls, now, duration, start_time=None):
        """
        Plan a window of duration seconds; now is a naive local datetime.
        It starts now, or at start_time (a time of day) today.
        """
        start = now.replace(second=0, microsecond=0)
        if start_time is not None:
            start = start.replace(
                hour=start_time.hour, minute=start_time.minute)
        start_ts = int(start.timestamp())
        end_ts = start_ts + duration
        if end_ts <= int(now.timestamp()):
            raise ZMaintError(
                'a window from {} lasting {}s is already over'.format(
                    format_ts(start_ts), duration))

        # Use calendar arithmetic; a day is not always 86400s long.
        today = now.date()
        end_day = datetime.fromtimestamp(end_ts).date()
        return cls(
            start_ts, duration,
            int(datetime.combine(today, dtime.min).timestamp()),
            int(datetime.combine(
                end_day + timedelta(days=1), dtime.min).timestamp()))


def format_ts(timestamp):
    return datetime.fromtimestamp(int(timestamp)).strftime('%Y-%m-%d %H:%M')


def maintenance_state(maintenance, now_ts):
    """
    Return (state, until_timestamp) for a maintenance as fetched by
    get_maintenances().

    The state is EXPIRED, ACTIVE or PENDING. This looks at the actual
    periods if all are one time only. For recurring periods, we cannot
    tell without more effort: those get RECURRING inside the active range.
    """
    since = int(maintenance['active_since'])
    till = int(maintenance['active_till'])
    periods = maintenance['timeperiods']

    if now_ts >= till:
        return 'EXPIRED', till
    if now_ts < since:
        return 'PENDING', till
    if all(int(p['timeperiod_type']) == 0 for p in periods):
        spans = [
            (int(p['start_date']), int(p['start_date']) + int(p['period']))
            for p in periods]
        for start, end in spans:
            if start <= now_ts < end:
                return 'ACTIVE', end
        last_end = max(end for start, end in spans)
        if now_ts < last_end:
            return 'PENDING', last_end
        return 'EXPIRED', last_end
    return 'RECURRING', till


MAINTENANCE_STATES = ('ACTIVE', 'PENDING', 'RECURRING', 'EXPIRED')


def parse_states(text):
    """
    Turn a comma separated list of states, or "any", into a set of the
    states as returned by maintenance_state().
    """
    states = set()
    for word in text.upper().split(','):
        if word == 'ANY':
            states.update(MAINTENANCE_STATES)
        elif word in MAINTENANCE_STATES:
            states.add(word)
        else:
            raise argparse.ArgumentTypeError(
                'invalid state {!r}, use any or a list of: {}'.format(
                    word.lower(), ', '.join(
                        state.lower() for state in MAINTENANCE_STATES)))
    return states


def format_states(states):
    return ','.join(
        state.lower() for state in MAINTENANCE_STATES if state in states)


def resolve_maintenance_targets(zint, patterns):
    """
    Find the hosts and host groups (written as @GROUP) for the patterns;
    fail if any matches nothing. Return (hosts, groups); the groups are
    dicts with groupid and name.

    This is stricter than a host lookup, because these hosts get their
    alerts silenced. A name without wildcards must match exactly one host
    (a lookup for "web" also finds "webmail"; here it does not). A pattern
    with wildcards must match the entire name and may match many.
    """
    hosts = []
    groups = []
    for pattern in patterns:
        if pattern.startswith('@'):
            if len(pattern) == 1:
                raise ZMaintError('an empty host group name after @')
            needle = Needle(pattern[1:])
            found = zint.get_hostgroups(needle)
            matches = [
                group for group in found
                if needle.is_exactly(group['name'])]
            if not matches:
                raise ZMaintError('no host group matches {!r}{}'.format(
                    pattern[1:], suggestions([g['name'] for g in found])))
            for group in matches:
                if group not in groups:
                    groups.append(group)
            continue

        needle = Needle(pattern)
        found = list(zint.get_hosts(needle))
        matches = [host for host in found if needle.is_exactly(host.name)]

        if not matches:
            raise ZMaintError('no host matches {!r}{}'.format(
                pattern, suggestions([host.name for host in found])))
        if len(matches) > 1 and not ('*' in pattern or '?' in pattern):
            raise ZMaintError(
                '{!r} matches {} hosts with that name (ids: {})'.format(
                    pattern, len(matches),
                    ', '.join(host._hostinfo['hostid'] for host in matches)))

        for host in matches:
            if host not in hosts:
                hosts.append(host)
    return hosts, groups


def suggestions(names):
    "Text for an error message: what was found instead."
    if not names:
        return ''
    return ' (did you mean: {}?)'.format(', '.join(sorted(names)))


def get_now():
    return datetime.now()


# Modes other than the default host lookup, in order of use. Each is picked
# with an option of the same name (--alerts) or an abbreviation of it.
MODES = ('alerts', 'data', 'maint')


class UsageError(ValueError):
    pass


def split_mode(argv):
    """
    Find the mode option in argv. Return (mode, remaining_argv).

    We cannot use argparse subcommands for this: the first positional
    argument is a (partial) hostname, and any word could be one.
    So the mode is an option instead. Any non-empty prefix of a mode name
    will do: --a, --al and --ale all select --alerts.
    """
    modes = set()
    remaining = []
    for i, arg in enumerate(argv):
        if arg == '--':
            remaining.extend(argv[i:])
            break
        if arg.startswith('--') and len(arg) > 2 and '=' not in arg:
            matches = [mode for mode in MODES if mode.startswith(arg[2:])]
            if len(matches) == 1:
                modes.add(matches[0])
                continue
        remaining.append(arg)

    if len(modes) > 1:
        raise UsageError('only one of {} may be given'.format(
            ', '.join('--' + mode for mode in MODES)))
    return (modes.pop() if modes else None), remaining


def connection_options(default=None):
    """
    Return a parser with the options for connecting, to be used as parent.

    For a parser with subparsers, give the subparsers default=SUPPRESS:
    otherwise their defaults overwrite what the parent already parsed.
    """
    connection = argparse.ArgumentParser(add_help=False)
    connection.add_argument(
        '-g', '--section', dest='section', default=default, help=(
            f'Use SECTION from {CONF_FILE} for defaults'))
    connection.add_argument(
        '-A', '--api', dest='api', default=default, help=(
            'Zabbix json_rpc API URL, for example: '
            'https://zabbix.example.nl/api_jsonrpc.php'))
    connection.add_argument(
        '-u', '--user', dest='user', default=default, help=(
            'API username'))
    connection.add_argument(
        '-p', '--password', dest='password', default=default, help=(
            'API password'))
    return connection


def build_parser(mode):
    "Build the argument parser for host lookups (mode=None) or a mode."
    connection = connection_options()

    if mode is None:
        parser = argparse.ArgumentParser(
            prog='zabdig', parents=[connection],
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description=(
                'Look up hosts by (part of) their name. If there is one '
                'exact match, only its address is printed (unless -l).'),
            epilog=(
                'Instead of a host lookup, one of these modes can be '
                'selected:\n'
                '  --alerts    show current alerts\n'
                '  --data      show latest item data\n'
                '  --maint     manage maintenance windows\n'
                '\n'
                'Mode names may be abbreviated (--ale). '
                'Use zabdig --MODE --help for details.'))
        parser.add_argument(
            '-l', '--list', action='store_true', help=(
                'Always list matching hosts, also if there is only one '
                'exact match'))
        parser.add_argument(
            '-x', '--with-ip', help=(
                'Filter by IP-address'))  # compare 'dig -x'
        parser.add_argument(
            '-v', '--verbose', action='store_true', help=(
                'Show details about every host'))
        parser.add_argument(
            'search', nargs='?', type=Needle, help=(
                'Hostname to search for (* and ? are allowed)'))
        parser.set_defaults(func=cmd_host)

    elif mode == 'alerts':
        parser = argparse.ArgumentParser(
            prog='zabdig --alerts', parents=[connection],
            description='Show current alerts.')
        parser.add_argument(
            '-S', '--alert-severity', default=3, type=int, help=(
                'Which severities to show, use bitmask: 0=all, '
                '1=disaster, 2=high, 4=avg, 8=warn, 16=info, 32=unclass '
                '(default: 3)'))
        parser.set_defaults(func=cmd_alerts)

    elif mode == 'data':
        parser = argparse.ArgumentParser(
            prog='zabdig --data', parents=[connection],
            description='Show the latest values of items on hosts.',
            epilog=(
                'Try --items=\'*\' on a single host to see available keys.'))
        parser.add_argument(
            '-i', '--items', action='append', required=True, help=(
                'Which items to show; the * is a supported wildcard. '
                'Can be used multiple times'))
        parser.add_argument(
            'search', nargs='?', type=Needle, help=(
                'Hostname to search for (* and ? are allowed)'))
        parser.set_defaults(func=cmd_data)

    elif mode == 'maint':
        sub_connection = connection_options(default=argparse.SUPPRESS)
        parser = argparse.ArgumentParser(
            prog='zabdig --maint', parents=[connection],
            description='Manage maintenance windows.')
        actions = parser.add_subparsers(
            dest='action', required=True, metavar='ACTION')

        list_action = actions.add_parser(
            'list', parents=[sub_connection],
            help='list maintenance windows',
            description='List unexpired maintenance windows.',
            epilog=(
                'Each line has the id, state, end, title, and the hosts '
                'and @hostgroups. The state is ACTIVE (in a time period), '
                'PENDING (starts later), RECURRING (has a recurring period '
                'and is not expired) or EXPIRED. Expired windows are only '
                'listed if selected with --state, for example: '
                '--state=any or --state=expired.'))
        list_action.add_argument(
            '--state', type=parse_states, default='active,pending,recurring',
            help=(
                'Only list windows in these states: any, or a comma '
                'separated list of active, pending, recurring, expired '
                '(default: %(default)s)'))

        create_action = actions.add_parser(
            'create', parents=[sub_connection],
            help='create a maintenance window',
            description=(
                'Create a one time maintenance window for one or more '
                'hosts, starting now or today at --start. Names without '
                'wildcards must match exactly one host. Wildcards (* and ?) '
                'must match entire host names. Prefix a name with @ to '
                'select a host group instead (@Linux).'))
        create_action.add_argument(
            '--start', type=parse_start, metavar='HH:MM', help=(
                'Start the window at this time today (local time) '
                'instead of now'))
        create_action.add_argument(
            'title', help='Title; must be unique')
        create_action.add_argument(
            'duration', type=parse_duration, help=(
                'How long, for example: 90m, 2h, 1h30m or 1d'))
        create_action.add_argument(
            'hosts', nargs='+', metavar='HOST|@GROUP', help=(
                'Hostname or @hostgroup (* and ? are allowed)'))

        add_action = actions.add_parser(
            'add', parents=[sub_connection],
            help='add hosts to a maintenance window',
            description=(
                'Add hosts and host groups to an existing maintenance '
                'window that has not expired. The targets are matched as '
                'for create.'))
        add_action.add_argument(
            'target', metavar='TITLE|ID', help=(
                'Title (exactly) or id of the maintenance window'))
        add_action.add_argument(
            'hosts', nargs='+', metavar='HOST|@GROUP', help=(
                'Hostname or @hostgroup (* and ? are allowed)'))

        remove_action = actions.add_parser(
            'remove', parents=[sub_connection],
            help='remove maintenance windows',
            description=(
                'Remove maintenance windows by title or id. The title may '
                'contain wildcards (* and ?) and match many windows: use '
                '--dry-run to see which.'))
        remove_action.add_argument(
            '--state', type=parse_states, help=(
                'Only remove windows in these states: any, or a comma '
                'separated list of active, pending, recurring, expired '
                '(default: any)'))
        remove_action.add_argument(
            '-n', '--dry-run', action='store_true', help=(
                'Only show which maintenance windows would be removed'))
        remove_action.add_argument(
            'targets', nargs='+', metavar='TITLE|ID', help=(
                'Id, or title of the maintenance window (* and ? are '
                'allowed)'))
        parser.set_defaults(func=cmd_maint)

    else:
        raise NotImplementedError(mode)

    return parser


def find_hosts(zint, search, with_ip=None, always_list=False):
    """
    Return the list of hosts matching the search, and whether that
    was narrowed down to a single exact match.
    """
    hosts = list(zint.get_hosts(search))
    if not hosts:
        print('nothing found', file=sys.stderr)
        return hosts, False

    # Limit hosts by IP address.
    # FIXME: perhaps do server-side search if possible here?
    if with_ip:
        hosts = [host for host in hosts if host.has_ip(with_ip)]

    # Unless the user asked for a list, if there is a single match, use that.
    if search and not always_list and not with_ip:
        exact_hosts = [host for host in hosts if search.is_exactly(host.name)]
        if len(exact_hosts) == 1:
            return exact_hosts, True

    return hosts, False


def cmd_host(zint, args):
    hosts, exact_match = find_hosts(
        zint, args.search, with_ip=args.with_ip, always_list=args.list)
    if not hosts:
        return 1

    # One match, show the IP.
    if exact_match and not args.verbose:
        print(hosts[0].get_zabbix_addr_first())
        return 0

    for host in sorted(hosts):
        if args.verbose:
            show_host(host)
        else:
            print('{name!s:30}  {addr!s}{optional_proxy!s}'.format(
                name=host,
                addr=host.get_zabbix_addr(),
                optional_proxy=(
                    host.proxy and ' ({!s})'.format(host.proxy) or '')))
    return 0


def cmd_alerts(zint, args):
    alerts = zint.get_alerts(args.alert_severity)
    for alert in alerts:
        print(alert)
    print(len(alerts))
    return 0


def cmd_data(zint, args):
    hosts, exact_match = find_hosts(zint, args.search)
    if not hosts:
        return 1
    if len(hosts) > 100:
        print('too many hosts selected', file=sys.stderr)
        return 1

    items = zint.get_latest_data(hosts, args.items)
    show_latest_data(hosts, items)
    return 0


def cmd_maint(zint, args):
    return {
        'list': cmd_maint_list,
        'create': cmd_maint_create,
        'add': cmd_maint_add,
        'remove': cmd_maint_remove,
    }[args.action](zint, args)


def cmd_maint_list(zint, args):
    now_ts = int(get_now().timestamp())

    rows = []
    for maintenance in zint.get_maintenances(args.state):
        state, until = maintenance_state(maintenance, now_ts)
        if state not in args.state:
            continue
        targets = sorted(host['name'] for host in maintenance['hosts'])
        targets.extend(sorted(
            '@' + group['name'] for group in maintenance['hostgroups']))
        rows.append((
            until, int(maintenance['maintenanceid']),
            '{:>6}  {:9}  {}  {}: {}'.format(
                maintenance['maintenanceid'], state, format_ts(until),
                maintenance['name'], ', '.join(targets))))

    for until, maintenanceid, row in sorted(rows):
        print(row)

    # Do not stay silent: an empty list looks like something is broken.
    if not rows:
        print('no maintenance windows in state {}'.format(
            format_states(args.state)), file=sys.stderr)
    return 0


def cmd_maint_create(zint, args):
    window = MaintenanceWindow.plan(get_now(), args.duration, args.start)
    hosts, groups = resolve_maintenance_targets(zint, args.hosts)

    if hosts:
        print('{} host{}: {}'.format(
            len(hosts), '' if len(hosts) == 1 else 's',
            ', '.join(sorted(host.name for host in hosts))), file=sys.stderr)
    if groups:
        print('{} host group{}: {}'.format(
            len(groups), '' if len(groups) == 1 else 's',
            ', '.join(sorted(group['name'] for group in groups))),
            file=sys.stderr)
    print('from {} until {}'.format(
        format_ts(window.start), format_ts(window.end)), file=sys.stderr)

    maintenanceid = zint.create_maintenance(
        args.title, [host._hostinfo['hostid'] for host in hosts],
        [group['groupid'] for group in groups], window.active_since,
        window.active_till, window.start, window.duration)
    print('created maintenance {} {!r} until {}'.format(
        maintenanceid, args.title, format_ts(window.end)))
    return 0


def cmd_maint_add(zint, args):
    maintenances = zint.get_maintenances()
    matches = [
        m for m in maintenances
        if m['maintenanceid'] == args.target or m['name'] == args.target]
    if not matches:
        raise ZMaintError('no maintenance with title or id {!r}'.format(
            args.target))
    if len(matches) > 1:
        raise ZMaintError(
            '{!r} is both a title and an id, use the id'.format(args.target))
    maintenance = matches[0]

    state, until = maintenance_state(
        maintenance, int(get_now().timestamp()))
    if state == 'EXPIRED':
        raise ZMaintError(
            'maintenance {} {!r} has expired; adding hosts to it does '
            'nothing'.format(
                maintenance['maintenanceid'], maintenance['name']))

    hosts, groups = resolve_maintenance_targets(zint, args.hosts)
    current_hostids = [host['hostid'] for host in maintenance['hosts']]
    current_groupids = [
        group['groupid'] for group in maintenance['hostgroups']]
    new_hosts = [
        host for host in hosts
        if host._hostinfo['hostid'] not in current_hostids]
    new_groups = [
        group for group in groups if group['groupid'] not in current_groupids]

    already = len(hosts) - len(new_hosts) + len(groups) - len(new_groups)
    if already:
        print('{} already in the maintenance, skipped'.format(already),
              file=sys.stderr)
    if not (new_hosts or new_groups):
        print('nothing to add to maintenance {} {!r}'.format(
            maintenance['maintenanceid'], maintenance['name']))
        return 0

    zint.update_maintenance(
        maintenance['maintenanceid'],
        hostids=(current_hostids + [
            host._hostinfo['hostid'] for host in new_hosts]
            if new_hosts else None),
        groupids=(current_groupids + [
            group['groupid'] for group in new_groups]
            if new_groups else None))
    print('added to maintenance {} {!r}: {}'.format(
        maintenance['maintenanceid'], maintenance['name'], ', '.join(
            sorted(host.name for host in new_hosts) +
            sorted('@' + group['name'] for group in new_groups))))
    return 0


def cmd_maint_remove(zint, args):
    maintenances = zint.get_maintenances(args.state)
    if args.state:
        now_ts = int(get_now().timestamp())
        maintenances = [
            m for m in maintenances
            if maintenance_state(m, now_ts)[0] in args.state]

    # Find everything first, so that nothing is removed if one fails.
    found = []
    for target in args.targets:
        has_wildcards = '*' in target or '?' in target
        title_regex = glob_to_regex(target)
        matches = [
            m for m in maintenances
            if m['maintenanceid'] == target or
            (title_regex.fullmatch(m['name']) if has_wildcards
             else m['name'] == target)]
        if not matches:
            raise ZMaintError('no maintenance with title or id {!r}{}'.format(
                target, ' in state ' + format_states(args.state)
                if args.state else ''))
        if len(matches) > 1 and not has_wildcards:
            raise ZMaintError(
                '{!r} is both a title and an id, use the id'.format(target))
        for maintenance in matches:
            if maintenance not in found:
                found.append(maintenance)

    # The server returns them in no particular order.
    found.sort(key=lambda m: int(m['maintenanceid']))

    if not args.dry_run:
        zint.delete_maintenances(m['maintenanceid'] for m in found)
    for maintenance in found:
        print('{} maintenance {} {!r}'.format(
            'would remove' if args.dry_run else 'removed',
            maintenance['maintenanceid'], maintenance['name']))
    return 0


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    try:
        mode, argv = split_mode(argv)
    except UsageError as e:
        print('zabdig: error: {}'.format(e), file=sys.stderr)
        return 2
    args = build_parser(mode).parse_args(argv)

    lconf = LocalConfig()
    if args.section:
        try:
            lconf.select_section(args.section)
        except ZConfigError:
            print('no such section found in config file', file=sys.stderr)
            return 1
    else:
        args.section = lconf.section

    api = args.api or lconf.get('api')
    user = args.user or lconf.get('user')
    password = args.password or lconf.get('password')

    # Ooh.. quick hacks!
    if not user or not password:
        (user, password) = get_from_secret_storage(args.section)

    try:
        zint = ZInterface(api, user, password)
    except ZConfigError as e:
        print(
            'login failed: {}; see zabdig --help'.format(e),
            file=sys.stderr)
        return 1

    try:
        return args.func(zint, args)
    except ZMaintError as e:
        print('zabdig: error: {}'.format(e), file=sys.stderr)
        return 1
    except ZInterfaceError as e:
        print('fetch failed: {}'.format(e), file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())

# vim: set ts=8 sw=4 sts=4 et ai:
